# Generated by Django 4.0.3 on 2022-04-29 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_store_productstore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryevent',
            options={'verbose_name': 'Акция на группу товаров', 'verbose_name_plural': 'Акция на группу товаров'},
        ),
        migrations.AlterModelOptions(
            name='productproperty',
            options={'verbose_name': 'Характеристики товара', 'verbose_name_plural': 'Характеристики товара'},
        ),
        migrations.AlterModelOptions(
            name='productstore',
            options={'verbose_name': 'Наличие товара', 'verbose_name_plural': 'Наличие товара'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
    ]
