# Generated by Django 4.0.3 on 2022-04-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_order_session_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='session',
        ),
        migrations.AddField(
            model_name='order',
            name='session_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
